
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const GET_SINGLE_PIN_SUCCESS = 'GET_SINGLE_PIN_SUCCESS'

export const ADD_COMMENT__SUCCESS = 'ADD_COMMENT__SUCCESS'

export const SAVE_PIN_SUCCESS = 'SAVE_PIN_SUCCESS'

export const LOGOUT_USER = 'LOGOUT_USER'

export const PIN_CREATOR_SUCCESS = 'PIN_CREATOR_SUCCESS'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CLEAR_ALERT = 'CLEAR_Alert'
export const SHOW_ALERT = 'SHOW_ALERT'

export const GET_PINS_BEGIN = 'GET_PINS_BEGIN'
export const GET_PINS_SUCCESS = 'GET_PINS_SUCCESS'
export const GET_PINS_ERROR = 'GET_PINS_ERROR'

export const BEGIN = 'BEGIN'
export const SUCCESS = 'SUCCESS'
export const ERROR = 'ERROR'

